name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Create env file
        run: |
          touch .env.local
          echo "DOUBAO_APIKEY=${{ secrets.DOUBAO_APIKEY }}" >> .env.local
          echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> .env.local
          echo "XF_APPID=${{ secrets.XF_APPID }}" >> .env.local
          echo "XF_APIKEY=${{ secrets.XF_APIKEY }}" >> .env.local
          echo "XF_APISECRET=${{ secrets.XF_APISECRET }}" >> .env.local
          echo "BAIDU_AK=${{ secrets.BAIDU_AK }}" >> .env.local

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true