name: Build and Push Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # 添加手动触发工作流的功能
  workflow_dispatch:

jobs:
  docker-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: zhanghj11/llm4se_hw3

      - name: Build and push Docker image (Linux)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: zhanghj11/llm4se_hw3:latest
          labels: ${{ steps.meta.outputs.labels }}

  docker-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          # Windows Docker 设置
          docker version

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build and push Docker image (Windows)
        run: |
          # 构建 Windows 容器镜像
          docker build -t zhanghj11/llm4se_hw3:windows-latest -f Dockerfile.windows .
          docker push zhanghj11/llm4se_hw3:windows-latest